### PR TITLE
Modified lib.html and views.py

### PR DESCRIPTION
**Pull request by vagdevik**

### CODE REVIEW

**Comment by savitha97** [comment]
@vagdevik  I fixed conflicts. Review.

**Comment by vagdevik** [comment]
View Assignments is not working. Please review it.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>




Thank you.
Regards,
K.Vagdevi.

**Comment by savitha97** [comment]
@vagdevik  I don't follow. Where is it not working? Read the code. If the code in master is not correct, make apt changes and make a pull request.

**Comment by savitha97** [comment]
View assignments is working in server.

**Pull request closed without merging**
